# Auto-generated by generate_pipeline.py

text_content = """
### 1. What is a Black Hole?
➔ A black hole is a region of spacetime where gravity is so strong that nothing—no particles or even electromagnetic radiation such as light—can escape from it.

### 2. Types of Black Holes:
**Stellar Black Holes:** Formed from the gravitational collapse of massive stars (typically 3 to tens of solar masses) at the end of their life cycle, these are the most common type of black hole observed in our galaxy. They are relatively small but incredibly dense, representing the remnants of supernova explosions.
**Supermassive Black Holes:** Residing at the centers of most large galaxies, including our own Milky Way, these colossal black holes range from millions to billions of times the mass of the Sun. Their formation mechanism is still debated but likely involves the merger of smaller black holes and accretion of vast amounts of gas and dust over cosmic timescales.
**Intermediate Black Holes:** With masses between 100 and 100,000 times that of the Sun, these hypothetical black holes bridge the gap between stellar and supermassive types. They are thought to form in dense star clusters and could potentially serve as "seeds" for supermassive black holes.
**Primordial Black Holes:** These theoretical black holes are thought to have formed in the very early universe, just moments after the Big Bang, from density fluctuations in the primordial plasma. Their masses could range from microscopic to thousands of solar masses, and if they exist, they could potentially contribute to dark matter.

### 3. Anatomy of a Black Hole:
**Event Horizon:** This is the boundary around a black hole beyond which nothing, not even light, can escape its gravitational pull. It is not a physical surface but rather a point of no return, where the escape velocity exceeds the speed of light.
**Singularity:** Located at the very center of a black hole, the singularity is a point of infinite density and zero volume where all the mass of the black hole is concentrated. Here, the laws of physics as we currently understand them break down.
**Accretion Disk:** A swirling, superheated disk of gas, dust, and stellar debris that spirals inward towards the event horizon of an active black hole. Friction within the disk heats the material to millions of degrees, causing it to emit intense X-rays and other radiation.
**Photon Sphere:** An unstable spherical region of spacetime around a black hole, just outside the event horizon, where gravity is so strong that photons (light particles) can orbit the black hole in a circular path. Any slight perturbation will cause them to either escape or fall into the black hole.
**Relativistic Jets:** Powerful, collimated beams of plasma emitted at nearly the speed of light from the poles of some active black holes, particularly those with accretion disks. These jets are thought to be powered by magnetic fields twisted by the spinning black hole and accretion disk, expelling material far into space.

### 4. Key Facts & Numbers:
*   The closest known black hole, Gaia BH1, is only about 1,560 light-years away from Earth.
*   The supermassive black hole at the center of our Milky Way galaxy, Sagittarius A*, has a mass equivalent to about 4.3 million Suns.
*   If you were to fall into a stellar-mass black hole, the intense tidal forces would stretch you into a long, thin strand, a process known as "spaghettification."
*   The largest known black hole, TON 618, is estimated to be 66 billion times the mass of our Sun, making it one of the most massive objects in the observable universe.

### 5. Importance and Exploration:
*   **Chandra X-ray Observatory:** This NASA telescope has been crucial for detecting X-rays emitted by hot gas spiraling into black holes and studying their relativistic jets, providing insights into their growth and impact on galaxies.
*   **Event Horizon Telescope (EHT):** A global network of radio telescopes that achieved the first-ever direct image of a black hole's event horizon (M87* in 2019 and Sagittarius A* in 2022), revolutionizing our understanding of these extreme objects.
*   **LIGO (Laser Interferometer Gravitational-Wave Observatory):** This ground-based observatory made the first direct detection of gravitational waves in 2015, confirming predictions of general relativity and opening a new window for observing black hole mergers.
"""

canvas_payload = r"""
const scene = new THREE.Scene();

const camera = new THREE.PerspectiveCamera(55, window.innerWidth / window.innerHeight, 0.01, 50000);
camera.position.set(0, 28, 72);
camera.lookAt(0, 0, 0);

const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: false });
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.1;
document.body.style.margin = '0';
document.body.style.overflow = 'hidden';
document.body.style.background = '#000';
document.body.appendChild(renderer.domElement);
renderer.domElement.style.position = 'fixed';
renderer.domElement.style.top = '0';
renderer.domElement.style.left = '0';
renderer.domElement.style.zIndex = '0';

const orbitControls = new window.OrbitControls(camera, renderer.domElement);
orbitControls.enableDamping  = true;
orbitControls.dampingFactor  = 0.04;
orbitControls.minDistance    = 14;
orbitControls.maxDistance    = 600;
orbitControls.enablePan      = false;
orbitControls.autoRotate     = true;
orbitControls.autoRotateSpeed = 0.12;

// ─── Starfield Background Sphere ──────────────────────────────────────────────
const bgLoader  = new THREE.TextureLoader();
const bgTex     = bgLoader.load(
  'https://raw.githubusercontent.com/jeromeetienne/threex.planets/master/images/galaxy_starfield.png',
  undefined,
  undefined,
  () => {
    // fallback: procedural stars if texture fails
    bgSphere.material.color.set(0x000005);
  }
);
const bgGeo  = new THREE.SphereGeometry(18000, 32, 32);
const bgMat  = new THREE.MeshBasicMaterial({ map: bgTex, side: THREE.BackSide, depthWrite: false });
const bgSphere = new THREE.Mesh(bgGeo, bgMat);
scene.add(bgSphere);

// ─── Procedural Glow Particle Texture (Canvas) ───────────────────────────────
function makeGlowCanvas(size) {
  const canvas  = document.createElement('canvas');
  canvas.width  = size;
  canvas.height = size;
  const ctx  = canvas.getContext('2d');
  const half = size / 2;
  const grad = ctx.createRadialGradient(half, half, 0, half, half, half);
  grad.addColorStop(0.0,  'rgba(255,255,255,1.0)');
  grad.addColorStop(0.08, 'rgba(255,255,255,0.95)');
  grad.addColorStop(0.25, 'rgba(255,240,200,0.7)');
  grad.addColorStop(0.50, 'rgba(255,180,80,0.35)');
  grad.addColorStop(0.75, 'rgba(200,80,20,0.12)');
  grad.addColorStop(1.0,  'rgba(0,0,0,0)');
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, size, size);
  return canvas;
}

const glowCanvas  = makeGlowCanvas(128);
const glowTexture = new THREE.CanvasTexture(glowCanvas);

// Sharper core texture for innermost particles
function makeCoreCanvas(size) {
  const canvas  = document.createElement('canvas');
  canvas.width  = size;
  canvas.height = size;
  const ctx  = canvas.getContext('2d');
  const half = size / 2;
  const grad = ctx.createRadialGradient(half, half, 0, half, half, half);
  grad.addColorStop(0.0,  'rgba(255,255,255,1.0)');
  grad.addColorStop(0.15, 'rgba(220,240,255,0.95)');
  grad.addColorStop(0.40, 'rgba(120,180,255,0.5)');
  grad.addColorStop(0.70, 'rgba(60,100,255,0.2)');
  grad.addColorStop(1.0,  'rgba(0,0,0,0)');
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, size, size);
  return canvas;
}
const coreTexture = new THREE.CanvasTexture(makeCoreCanvas(128));

// ─── Event Horizon (Black Sphere) ────────────────────────────────────────────
const EH_RADIUS   = 8.0;
const ehGeo = new THREE.SphereGeometry(EH_RADIUS, 64, 64);
const ehMat = new THREE.MeshBasicMaterial({ color: 0x000000 });
const ehMesh = new THREE.Mesh(ehGeo, ehMat);
ehMesh.renderOrder = 2;
scene.add(ehMesh);

// ─── Photon Sphere / Gravitational Lensing Aura ───────────────────────────────
const photonGeo = new THREE.SphereGeometry(EH_RADIUS * 1.5, 64, 64);
const photonMat = new THREE.MeshBasicMaterial({
  color:       0x44aaff,
  transparent: true,
  opacity:     0.06,
  side:        THREE.BackSide,
  depthWrite:  false,
});
scene.add(new THREE.Mesh(photonGeo, photonMat));

const photonGeo2 = new THREE.SphereGeometry(EH_RADIUS * 1.28, 64, 64);
const photonMat2 = new THREE.MeshBasicMaterial({
  color:       0x88ccff,
  transparent: true,
  opacity:     0.09,
  side:        THREE.BackSide,
  depthWrite:  false,
});
scene.add(new THREE.Mesh(photonGeo2, photonMat2));

// Razor-thin photon ring glow
const ringCurve = new THREE.TorusGeometry(EH_RADIUS * 1.47, 0.18, 16, 200);
const ringMat   = new THREE.MeshBasicMaterial({ color: 0xaaddff, transparent: true, opacity: 0.22, depthWrite: false });
const photonRing = new THREE.Mesh(ringCurve, ringMat);
photonRing.rotation.x = Math.PI / 2;
scene.add(photonRing);

// ─── Accretion Disk Particle System ─────────────────────────────────────────
const DISK_PARTICLE_COUNT = 46000;
const INNER_RADIUS = EH_RADIUS * 1.55;
const OUTER_RADIUS = EH_RADIUS * 9.0;

const diskPositions   = new Float32Array(DISK_PARTICLE_COUNT * 3);
const diskColors      = new Float32Array(DISK_PARTICLE_COUNT * 3);
const diskSizes       = new Float32Array(DISK_PARTICLE_COUNT);
const diskAngles      = new Float32Array(DISK_PARTICLE_COUNT);
const diskRadii       = new Float32Array(DISK_PARTICLE_COUNT);
const diskYOffsets    = new Float32Array(DISK_PARTICLE_COUNT);
const diskSpeeds      = new Float32Array(DISK_PARTICLE_COUNT);
const diskColorType   = new Uint8Array(DISK_PARTICLE_COUNT);

// Color palette: 0=core blue-white, 1=inner white, 2=hot orange, 3=mid orange, 4=outer red
function getParticleColor(normalizedR) {
  if (normalizedR < 0.12) return { r: 0.7, g: 0.88, b: 1.0 };   // blue-white core
  if (normalizedR < 0.22) return { r: 1.0, g: 1.0,  b: 1.0 };   // brilliant white
  if (normalizedR < 0.35) return { r: 1.0, g: 0.92, b: 0.6 };   // hot yellow-white
  if (normalizedR < 0.50) return { r: 1.0, g: 0.75, b: 0.2 };   // bright yellow-orange
  if (normalizedR < 0.65) return { r: 1.0, g: 0.48, b: 0.08 };  // deep orange
  if (normalizedR < 0.80) return { r: 0.9, g: 0.25, b: 0.04 };  // orange-red
  return { r: 0.6, g: 0.08, b: 0.02 };                           // deep crimson
}

for (let i = 0; i < DISK_PARTICLE_COUNT; i++) {
  // Bias distribution toward inner disk (where density is higher)
  const raw = Math.pow(Math.random(), 0.55);
  const r   = INNER_RADIUS + raw * (OUTER_RADIUS - INNER_RADIUS);
  const nR  = (r - INNER_RADIUS) / (OUTER_RADIUS - INNER_RADIUS);
  const angle = Math.random() * Math.PI * 2;

  // Vertical spread: thin disk, thicker at edges
  const ySpread = (0.08 + nR * 0.4) * r * 0.05;
  const y       = (Math.random() - 0.5) * ySpread;

  diskAngles[i]   = angle;
  diskRadii[i]    = r;
  diskYOffsets[i] = y;

  // Keplerian: angular velocity ∝ r^(-3/2)
  diskSpeeds[i]   = Math.pow(r, -1.42) * 28.0;

  diskPositions[i * 3]     = Math.cos(angle) * r;
  diskPositions[i * 3 + 1] = y;
  diskPositions[i * 3 + 2] = Math.sin(angle) * r;

  const col = getParticleColor(nR);
  // Brightness variation
  const bright = 0.55 + Math.random() * 0.45;
  diskColors[i * 3]     = col.r * bright;
  diskColors[i * 3 + 1] = col.g * bright;
  diskColors[i * 3 + 2] = col.b * bright;

  // Particle size: larger/brighter near center
  diskSizes[i] = (nR < 0.25) ? 1.8 + Math.random() * 2.2
               : (nR < 0.55) ? 1.2 + Math.random() * 1.4
               :                0.6 + Math.random() * 1.0;
}

const diskGeo = new THREE.BufferGeometry();
diskGeo.setAttribute('position', new THREE.BufferAttribute(diskPositions, 3));
diskGeo.setAttribute('color',    new THREE.BufferAttribute(diskColors, 3));
diskGeo.setAttribute('size',     new THREE.BufferAttribute(diskSizes, 1));

const diskMat = new THREE.PointsMaterial({
  size:            1.4,
  map:             glowTexture,
  vertexColors:    true,
  transparent:     true,
  opacity:         0.92,
  blending:        THREE.AdditiveBlending,
  depthWrite:      false,
  sizeAttenuation: true,
});

const diskPoints = new THREE.Points(diskGeo, diskMat);
diskPoints.renderOrder = 1;
scene.add(diskPoints);

// ─── Secondary Thin Bright Ring (photon capture region) ──────────────────────
const RING2_COUNT = 6000;
const ring2Pos    = new Float32Array(RING2_COUNT * 3);
const ring2Col    = new Float32Array(RING2_COUNT * 3);
const ring2Sz     = new Float32Array(RING2_COUNT);
const ring2Ang    = new Float32Array(RING2_COUNT);
const ring2Rad    = new Float32Array(RING2_COUNT);
const ring2Spd    = new Float32Array(RING2_COUNT);

for (let i = 0; i < RING2_COUNT; i++) {
  const r     = EH_RADIUS * (1.50 + Math.random() * 0.22);
  const angle = Math.random() * Math.PI * 2;
  const y     = (Math.random() - 0.5) * 0.25;
  ring2Ang[i] = angle;
  ring2Rad[i] = r;
  ring2Spd[i] = Math.pow(r, -1.42) * 30.0;
  ring2Pos[i * 3]     = Math.cos(angle) * r;
  ring2Pos[i * 3 + 1] = y;
  ring2Pos[i * 3 + 2] = Math.sin(angle) * r;
  ring2Col[i * 3]     = 0.55 + Math.random() * 0.45;
  ring2Col[i * 3 + 1] = 0.75 + Math.random() * 0.25;
  ring2Col[i * 3 + 2] = 1.0;
  ring2Sz[i]  = 1.2 + Math.random() * 2.0;
}

const ring2Geo = new THREE.BufferGeometry();
ring2Geo.setAttribute('position', new THREE.BufferAttribute(ring2Pos, 3));
ring2Geo.setAttribute('color',    new THREE.BufferAttribute(ring2Col, 3));
ring2Geo.setAttribute('size',     new THREE.BufferAttribute(ring2Sz, 1));

const ring2Mat = new THREE.PointsMaterial({
  size:            1.8,
  map:             coreTexture,
  vertexColors:    true,
  transparent:     true,
  opacity:         0.75,
  blending:        THREE.AdditiveBlending,
  depthWrite:      false,
  sizeAttenuation: true,
});
const ring2Points = new THREE.Points(ring2Geo, ring2Mat);
ring2Points.renderOrder = 1;
scene.add(ring2Points);

// ─── Ambient Jets (relativistic particle jets perpendicular to disk) ──────────
const JET_COUNT = 5000;
const jetPos    = new Float32Array(JET_COUNT * 3);
const jetCol    = new Float32Array(JET_COUNT * 3);
const jetSz     = new Float32Array(JET_COUNT);
const jetVY     = new Float32Array(JET_COUNT);
const jetVX     = new Float32Array(JET_COUNT);
const jetVZ     = new Float32Array(JET_COUNT);
const jetLife   = new Float32Array(JET_COUNT);
const jetMaxLife= new Float32Array(JET_COUNT);

function initJetParticle(i, sign) {
  const spread = 0.6 + Math.random() * 0.8;
  const speed  = 3.5 + Math.random() * 5.0;
  const angle  = Math.random() * Math.PI * 2;
  jetPos[i * 3]     = Math.cos(angle) * spread * 0.4;
  jetPos[i * 3 + 1] = sign * (EH_RADIUS * 0.8 + Math.random() * 1.2);
  jetPos[i * 3 + 2] = Math.sin(angle) * spread * 0.4;
  jetVX[i]     = Math.cos(angle) * spread * 0.06;
  jetVY[i]     = sign * speed;
  jetVZ[i]     = Math.sin(angle) * spread * 0.06;
  jetLife[i]   = Math.random();
  jetMaxLife[i]= 2.0 + Math.random() * 3.5;
  const t      = Math.random();
  jetCol[i * 3]     = 0.4 + t * 0.4;
  jetCol[i * 3 + 1] = 0.6 + t * 0.35;
  jetCol[i * 3 + 2] = 1.0;
  jetSz[i]     = 0.8 + Math.random() * 1.6;
}

for (let i = 0; i < JET_COUNT; i++) {
  initJetParticle(i, i % 2 === 0 ? 1 : -1);
}

const jetGeo = new THREE.BufferGeometry();
jetGeo.setAttribute('position', new THREE.BufferAttribute(jetPos, 3));
jetGeo.setAttribute('color',    new THREE.BufferAttribute(jetCol, 3));
jetGeo.setAttribute('size',     new THREE.BufferAttribute(jetSz,  1));

const jetMat = new THREE.PointsMaterial({
  size:            1.2,
  map:             coreTexture,
  vertexColors:    true,
  transparent:     true,
  opacity:         0.55,
  blending:        THREE.AdditiveBlending,
  depthWrite:      false,
  sizeAttenuation: true,
});
const jetPoints = new THREE.Points(jetGeo, jetMat);
jetPoints.renderOrder = 1;
scene.add(jetPoints);

// ─── Central Glow Volume ──────────────────────────────────────────────────────
function addGlowLayer(radius, color, opacity) {
  const g = new THREE.SphereGeometry(radius, 32, 32);
  const m = new THREE.MeshBasicMaterial({ color, transparent: true, opacity, side: THREE.BackSide, depthWrite: false });
  const mesh = new THREE.Mesh(g, m);
  mesh.renderOrder = 0;
  scene.add(mesh);
  return mesh;
}
addGlowLayer(EH_RADIUS * 2.2, 0xff6600, 0.055);
addGlowLayer(EH_RADIUS * 3.0, 0xff3300, 0.030);
addGlowLayer(EH_RADIUS * 4.5, 0xcc1100, 0.015);
addGlowLayer(EH_RADIUS * 6.0, 0x660000, 0.010);

// ─── Foreground Black Hole Occlusion Disc (hides disk behind EH) ──────────────
const occGeo  = new THREE.SphereGeometry(EH_RADIUS * 1.005, 48, 48);
const occMat  = new THREE.MeshBasicMaterial({ color: 0x000000, depthWrite: true });
const occMesh = new THREE.Mesh(occGeo, occMat);
occMesh.renderOrder = 3;
scene.add(occMesh);

// ─── HTML UI ──────────────────────────────────────────────────────────────────
const FONT    = "'Segoe UI','Helvetica Neue',Arial,sans-serif";
const GLASS   = 'rgba(4,2,10,0.88)';
const BORDER  = 'rgba(120,60,200,0.22)';

function domEl(tag, css, html) {
  const d = document.createElement(tag);
  if (css)  d.style.cssText = css;
  if (html) d.innerHTML = html;
  document.body.appendChild(d);
  return d;
}

// ─── Educational Side Panel ───────────────────────────────────────────────────
const sidePanel = domEl('div',
  `position:fixed;top:0;left:0;width:272px;height:100vh;z-index:110;
   backdrop-filter:blur(20px);background:${GLASS};
   border-right:1px solid ${BORDER};font-family:${FONT};
   overflow-y:auto;display:flex;flex-direction:column;
   scrollbar-width:thin;scrollbar-color:#1a0a2a transparent;`
);

sidePanel.innerHTML = `
<div style="padding:24px 20px 16px;border-bottom:1px solid rgba(80,30,140,0.35)">
  <div style="font-size:10px;letter-spacing:3px;color:#2a1040;text-transform:uppercase;margin-bottom:8px">Deep Space Object</div>
  <div style="font-size:22px;font-weight:700;color:#c8a8ff;letter-spacing:1px;line-height:1.2">Supermassive<br>Black Hole</div>
  <div style="font-size:11px;color:#5a3080;margin-top:6px;line-height:1.6">M87* class · ~6.5 billion M☉</div>
</div>

<div style="padding:16px 20px;border-bottom:1px solid rgba(60,20,100,0.3)">
  <div style="font-size:10px;letter-spacing:2px;color:#3a1060;text-transform:uppercase;margin-bottom:10px">Anatomy</div>

  <div style="margin-bottom:16px">
    <div style="display:flex;align-items:center;gap:8px;margin-bottom:5px">
      <div style="width:8px;height:8px;border-radius:50%;background:#ffffff;flex-shrink:0"></div>
      <div style="font-size:13px;font-weight:600;color:#e0d0ff">The Singularity</div>
    </div>
    <p style="font-size:11.5px;color:#5a4080;line-height:1.70;margin:0">
      A point of <b style="color:#9a70cc">infinite density</b> and zero volume at the center. All matter that crosses the event horizon is compressed here. General Relativity breaks down — physics as we know it ceases to exist at the singularity.
    </p>
  </div>

  <div style="margin-bottom:16px">
    <div style="display:flex;align-items:center;gap:8px;margin-bottom:5px">
      <div style="width:8px;height:8px;border-radius:50%;background:#4444ff;flex-shrink:0"></div>
      <div style="font-size:13px;font-weight:600;color:#e0d0ff">Event Horizon</div>
    </div>
    <p style="font-size:11.5px;color:#5a4080;line-height:1.70;margin:0">
      The <b style="color:#9a70cc">point of no return</b>. The boundary where escape velocity equals the speed of light. Nothing — not even photons — can escape once inside. For M87*, this sphere is ~38 billion km across.
    </p>
  </div>

  <div style="margin-bottom:16px">
    <div style="display:flex;align-items:center;gap:8px;margin-bottom:5px">
      <div style="width:8px;height:8px;border-radius:50%;background:#ff6600;flex-shrink:0"></div>
      <div style="font-size:13px;font-weight:600;color:#e0d0ff">Accretion Disk</div>
    </div>
    <p style="font-size:11.5px;color:#5a4080;line-height:1.70;margin:0">
      Superheated plasma spiraling inward at <b style="color:#9a70cc">relativistic speeds</b>. Friction heats the inner disk to billions of degrees — hotter than most stellar interiors — releasing X-ray and gamma radiation. The blue-white core reaches ~10 billion K.
    </p>
  </div>

  <div style="margin-bottom:16px">
    <div style="display:flex;align-items:center;gap:8px;margin-bottom:5px">
      <div style="width:8px;height:8px;border-radius:50%;background:#ff2244;flex-shrink:0"></div>
      <div style="font-size:13px;font-weight:600;color:#e0d0ff">Spaghettification</div>
    </div>
    <p style="font-size:11.5px;color:#5a4080;line-height:1.70;margin:0">
      Extreme <b style="color:#9a70cc">tidal forces</b> stretch any infalling object into a long strand of matter — like cosmic spaghetti. The gravitational pull on the near side of an object vastly exceeds that on the far side, tearing it apart before it even crosses the horizon.
    </p>
  </div>

  <div style="margin-bottom:4px">
    <div style="display:flex;align-items:center;gap:8px;margin-bottom:5px">
      <div style="width:8px;height:8px;border-radius:50%;background:#5599ff;flex-shrink:0"></div>
      <div style="font-size:13px;font-weight:600;color:#e0d0ff">Relativistic Jets</div>
    </div>
    <p style="font-size:11.5px;color:#5a4080;line-height:1.70;margin:0">
      Twin plasma jets ejected perpendicular to the disk at <b style="color:#9a70cc">near light speed</b>. Powered by the Blandford–Znajek mechanism — magnetic fields extract rotational energy from the spinning black hole itself. M87's jet extends 5,000 light-years.
    </p>
  </div>
</div>

<div style="padding:16px 20px">
  <div style="font-size:10px;letter-spacing:2px;color:#3a1060;text-transform:uppercase;margin-bottom:10px">Key Facts</div>
  <div style="font-size:11.5px;color:#4a3070;line-height:2.0">
    <div style="display:flex;justify-content:space-between;border-bottom:1px solid rgba(60,20,100,0.25);padding:2px 0">
      <span>Schwarzschild radius</span><b style="color:#7a50aa">∝ Mass</b>
    </div>
    <div style="display:flex;justify-content:space-between;border-bottom:1px solid rgba(60,20,100,0.25);padding:2px 0">
      <span>Time dilation at horizon</span><b style="color:#7a50aa">→ ∞</b>
    </div>
    <div style="display:flex;justify-content:space-between;border-bottom:1px solid rgba(60,20,100,0.25);padding:2px 0">
      <span>Hawking temperature</span><b style="color:#7a50aa">~10⁻¹⁴ K</b>
    </div>
    <div style="display:flex;justify-content:space-between;border-bottom:1px solid rgba(60,20,100,0.25);padding:2px 0">
      <span>Photon sphere</span><b style="color:#7a50aa">1.5 × r_s</b>
    </div>
    <div style="display:flex;justify-content:space-between;padding:2px 0">
      <span>First imaged</span><b style="color:#7a50aa">April 2019</b>
    </div>
  </div>
</div>
`;

// ─── Bottom Control Panel ─────────────────────────────────────────────────────
const ctrlPanel = domEl('div',
  `position:fixed;bottom:0;left:272px;right:0;z-index:110;
   backdrop-filter:blur(18px);background:rgba(2,1,8,0.90);
   border-top:1px solid ${BORDER};padding:14px 28px;
   display:flex;align-items:center;gap:24px;font-family:${FONT};
   flex-wrap:wrap;justify-content:center;`
);

// Time Warp Slider
const twLabel = document.createElement('div');
twLabel.style.cssText = `color:#4a2080;font-size:12px;white-space:nowrap;`;
twLabel.textContent = 'Time Warp:';
ctrlPanel.appendChild(twLabel);

const twDisplay = document.createElement('div');
twDisplay.style.cssText = `color:#7a40aa;font-size:11.5px;min-width:40px;`;
twDisplay.textContent = '1.0×';
ctrlPanel.appendChild(twDisplay);

const twSlider = document.createElement('input');
twSlider.type  = 'range';
twSlider.min   = '0';
twSlider.max   = '100';
twSlider.value = '38';
twSlider.style.cssText = 'width:130px;accent-color:#8844cc;cursor:pointer;';
ctrlPanel.appendChild(twSlider);

let timeWarp = 1.0;
twSlider.addEventListener('input', () => {
  const v  = parseFloat(twSlider.value);
  timeWarp = Math.pow(10, (v / 100) * 3) * 0.1;
  twDisplay.textContent = timeWarp < 1 ? timeWarp.toFixed(2) + '×' : timeWarp.toFixed(1) + '×';
});

const sep = document.createElement('div');
sep.style.cssText = `width:1px;height:26px;background:rgba(80,30,120,0.4);`;
ctrlPanel.appendChild(sep);

// Toggle Disk
const diskBtn = document.createElement('button');
diskBtn.innerHTML = '&#11835; Disk ON';
diskBtn.style.cssText = `background:rgba(6,2,16,0.9);border:1px solid rgba(100,50,180,0.40);
  color:#7a50aa;border-radius:8px;padding:8px 16px;cursor:pointer;
  font-family:${FONT};font-size:12.5px;transition:border-color 0.2s,color 0.2s;`;
diskBtn.onmouseenter = () => { diskBtn.style.borderColor = 'rgba(160,100,255,0.8)'; diskBtn.style.color = '#c090ff'; };
diskBtn.onmouseleave = () => { diskBtn.style.borderColor = 'rgba(100,50,180,0.40)'; diskBtn.style.color = '#7a50aa'; };
ctrlPanel.appendChild(diskBtn);

let diskVisible = true;
diskBtn.addEventListener('click', () => {
  diskVisible = !diskVisible;
  diskPoints.visible  = diskVisible;
  ring2Points.visible = diskVisible;
  diskBtn.innerHTML   = diskVisible ? '&#11835; Disk ON' : '&#11835; Disk OFF';
});

const sep2 = document.createElement('div');
sep2.style.cssText = `width:1px;height:26px;background:rgba(80,30,120,0.4);`;
ctrlPanel.appendChild(sep2);

// Toggle Jets
const jetBtn = document.createElement('button');
jetBtn.innerHTML = '&#8657; Jets ON';
jetBtn.style.cssText = `background:rgba(6,2,16,0.9);border:1px solid rgba(100,50,180,0.40);
  color:#5060aa;border-radius:8px;padding:8px 16px;cursor:pointer;
  font-family:${FONT};font-size:12.5px;transition:border-color 0.2s,color 0.2s;`;
jetBtn.onmouseenter = () => { jetBtn.style.borderColor = 'rgba(100,140,255,0.8)'; jetBtn.style.color = '#88aaff'; };
jetBtn.onmouseleave = () => { jetBtn.style.borderColor = 'rgba(100,50,180,0.40)'; jetBtn.style.color = '#5060aa'; };
ctrlPanel.appendChild(jetBtn);

let jetsVisible = true;
jetBtn.addEventListener('click', () => {
  jetsVisible       = !jetsVisible;
  jetPoints.visible = jetsVisible;
  jetBtn.innerHTML  = jetsVisible ? '&#8657; Jets ON' : '&#8657; Jets OFF';
});

const sep3 = document.createElement('div');
sep3.style.cssText = `width:1px;height:26px;background:rgba(80,30,120,0.4);`;
ctrlPanel.appendChild(sep3);

// Auto-rotate toggle
const rotBtn = document.createElement('button');
rotBtn.innerHTML = '&#8635; Orbit ON';
rotBtn.style.cssText = `background:rgba(6,2,16,0.9);border:1px solid rgba(100,50,180,0.40);
  color:#7a50aa;border-radius:8px;padding:8px 16px;cursor:pointer;
  font-family:${FONT};font-size:12.5px;transition:border-color 0.2s,color 0.2s;`;
rotBtn.onmouseenter = () => { rotBtn.style.borderColor = 'rgba(160,100,255,0.8)'; rotBtn.style.color = '#c090ff'; };
rotBtn.onmouseleave = () => { rotBtn.style.borderColor = 'rgba(100,50,180,0.40)'; rotBtn.style.color = '#7a50aa'; };
ctrlPanel.appendChild(rotBtn);

rotBtn.addEventListener('click', () => {
  orbitControls.autoRotate = !orbitControls.autoRotate;
  rotBtn.innerHTML = orbitControls.autoRotate ? '&#8635; Orbit ON' : '&#8635; Orbit OFF';
});

// ─── Tooltip ──────────────────────────────────────────────────────────────────
const tooltip = domEl('div',
  `position:fixed;z-index:200;display:none;pointer-events:none;
   background:rgba(4,2,12,0.95);border:1px solid rgba(120,60,200,0.45);
   border-radius:10px;padding:10px 15px;font-family:${FONT};font-size:12px;
   color:#a080cc;box-shadow:0 0 22px rgba(100,40,200,0.28);line-height:1.8;`
);

// ─── Raycaster ────────────────────────────────────────────────────────────────
const raycaster = new THREE.Raycaster();
raycaster.params.Points.threshold = 0.5;
const mouse = new THREE.Vector2(-9999, -9999);

window.addEventListener('mousemove', e => {
  mouse.x =  (e.clientX / window.innerWidth)  * 2 - 1;
  mouse.y = -(e.clientY / window.innerHeight) * 2 + 1;
  tooltip.style.left = (e.clientX + 16) + 'px';
  tooltip.style.top  = (e.clientY - 14) + 'px';
});

window.addEventListener('mousemove', e => {
  raycaster.setFromCamera(mouse, camera);
  const hits = raycaster.intersectObject(ehMesh);
  if (hits.length > 0) {
    tooltip.style.display = 'block';
    tooltip.innerHTML = `<b style="color:#cc88ff">Event Horizon</b><br>
      Escape velocity: <b>c</b><br>
      Radius: <b>${EH_RADIUS} (scaled)</b><br>
      <span style="color:#4a2070;font-size:11px">Nothing escapes from here</span>`;
  } else {
    tooltip.style.display = 'none';
  }
});

// ─── Animation Clock ──────────────────────────────────────────────────────────
const clock = new THREE.Clock();
let elapsedTime = 0;

// Accretion disk shimmer colors (shift slightly over time for heat flicker)
const colorShiftPeriod = 1.8;

function animate() {
  requestAnimationFrame(animate);
  const delta      = clock.getDelta();
  const animDelta  = delta * timeWarp;
  elapsedTime     += animDelta;

  orbitControls.update();

  // ── Animate Disk Particles ──────────────────────────────────────────────────
  const posAttr = diskGeo.attributes.position;
  const colAttr = diskGeo.attributes.color;

  for (let i = 0; i < DISK_PARTICLE_COUNT; i++) {
    diskAngles[i] += diskSpeeds[i] * animDelta;
    const r   = diskRadii[i];
    const ang = diskAngles[i];
    posAttr.setXYZ(i,
      Math.cos(ang) * r,
      diskYOffsets[i],
      Math.sin(ang) * r
    );

    // Subtle color shimmer for inner particles
    const nR = (r - INNER_RADIUS) / (OUTER_RADIUS - INNER_RADIUS);
    if (nR < 0.35) {
      const flicker = 0.75 + 0.25 * Math.sin(elapsedTime * 8.0 + i * 0.07);
      const col     = getParticleColor(nR);
      colAttr.setXYZ(i,
        col.r * flicker,
        col.g * flicker * 0.97,
        col.b * flicker
      );
    }
  }
  posAttr.needsUpdate = true;
  colAttr.needsUpdate = true;

  // ── Animate Inner Ring (photon ring) ────────────────────────────────────────
  const r2pos = ring2Geo.attributes.position;
  for (let i = 0; i < RING2_COUNT; i++) {
    ring2Ang[i] += ring2Spd[i] * animDelta * 1.35;
    const r   = ring2Rad[i];
    const ang = ring2Ang[i];
    r2pos.setXYZ(i, Math.cos(ang) * r, ring2Geo.attributes.position.getY(i), Math.sin(ang) * r);
  }
  r2pos.needsUpdate = true;

  // ── Animate Jets ────────────────────────────────────────────────────────────
  const jPos = jetGeo.attributes.position;
  const jCol = jetGeo.attributes.color;
  for (let i = 0; i < JET_COUNT; i++) {
    jetLife[i] += delta / jetMaxLife[i];
    if (jetLife[i] > 1.0) {
      initJetParticle(i, i % 2 === 0 ? 1 : -1);
      continue;
    }
    const lt      = jetLife[i];
    const fade    = Math.sin(lt * Math.PI);
    const scatX   = jetPos[i * 3]     + jetVX[i] * animDelta * 0.5;
    const scatY   = jetPos[i * 3 + 1] + jetVY[i] * animDelta * 0.25;
    const scatZ   = jetPos[i * 3 + 2] + jetVZ[i] * animDelta * 0.5;
    jetPos[i * 3]     = scatX;
    jetPos[i * 3 + 1] = scatY;
    jetPos[i * 3 + 2] = scatZ;
    jPos.setXYZ(i, scatX, scatY, scatZ);
    jCol.setXYZ(i,
      jetCol[i * 3]     * fade * (0.6 + 0.4 * Math.sin(elapsedTime * 5.0 + i)),
      jetCol[i * 3 + 1] * fade,
      jetCol[i * 3 + 2] * fade
    );
  }
  jPos.needsUpdate = true;
  jCol.needsUpdate = true;

  // ── Photon ring pulse ────────────────────────────────────────────────────────
  const pr = 1.0 + 0.025 * Math.sin(elapsedTime * 2.2);
  photonRing.scale.setScalar(pr);
  photonRing.material.opacity = 0.18 + 0.06 * Math.sin(elapsedTime * 3.1);

  // ── Sun lens flare glow shimmer ───────────────────────────────────────────
  photonMat.opacity  = 0.055 + 0.022 * Math.sin(elapsedTime * 1.4);
  photonMat2.opacity = 0.085 + 0.030 * Math.sin(elapsedTime * 1.9 + 0.8);

  // ── Background slow drift ────────────────────────────────────────────────
  bgSphere.rotation.y += delta * 0.0004;

  renderer.render(scene, camera);
}

window.addEventListener('resize', () => {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
  ctrlPanel.style.left = '272px';
});

animate();
"""

def get_blackhole_content():
    return {
        "title": "Black Hole",
        "text_explanation": text_content,
        "media_type": "3D_simulation",
        "code": canvas_payload
    }
